---
title: "CMDA-4654  \nHomework 01"
subtitle: "Homework 01"
author: "Junwoo Seo"
date: "Sep 17, 2024"
output:
  pdf_document:
    highlight: haddock
keep_tex: no
number_sections: no
html_document:
  df_print: paged
geometry: margin = 0.5in
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage{xcolor}
editor_options:
  chunk_output_type: console
documentclass: article
urlcolor: blue
---
  
<!-- The above is set to automatically compile to a .pdf file.   -->
<!-- It will only succeed if LaTeX is installed. -->


```{r setup, include=FALSE}
# This is the setup chunk
#  Here you can set global options for the entire document

library(knitr) # I recommend doing this here

# Although you can call functions from a library using the following notation
#  without loading the entire library.
knitr::opts_chunk$set(echo = TRUE, 
                      comment = NA, # Required
                      fig.path = "./figures/",  # Store all figures here in relative path (make the folder first)
                      fig.align = "center",
                      fig.width = 7,
                      fig.height = 7,
                      message = FALSE, # Turn off load messages
                      warning = FALSE # Turn off warnings
                      )

```

\clearpage

```{r include=FALSE}
# You should not echo this chunk.
# include=FALSE does more than echo=FALSE, it actually does: echo=FALSE, results='hide', message=FALSE, warning=FALSE, fig.show='hide'

# You should set your working directory at the very beginning of your R Markdown file
# setwd("~/Dropbox/teaching/FA2020/CMDA_4654/homework/homework1/")

# In linux ~/ is shorthand for /home/username/
# You should type things out properly for your system
# Mac: /Users/username/Documents/CMDA4654/Lectures/Lecture_03/.../
# Windows: C:/Users/username/Documents/etc/Lecture/Lecture_03/.../


```

<!-- ---------------------------------------------------------------------------------------------------- -->
<!-- ---------------- Homework Problems start below these lines ----------------------------------------- -->
<!-- ---------------------------------------------------------------------------------------------------- -->


# Problem 1

## Part (a): Calculate $P(Y_{1} \gt 1, Y_{2} < 1)$

For the Joint Density Funtion for this question is: 


\[
  f(y_1, y_2) =
  \begin{cases} 
  \frac{1}{8} y_1 e^{-\frac{(y_1 + y_2)}{2}}, & \text{if } y_1 > 0 \text{ and } y_2 > 0 \\
  0, & \text{otherwise}
  \end{cases}
\]

To calculate the $P(Y_{1} \gt 1, Y_{2} < 1)$, we need to use the integration of the joint density function.To specifiy, the integration would look like:

- $\int_{0}^{1} \int_{1}^{\infty} f(x) \; dy_{1} dy_{2}$

Now, to calculate the above, write the r code as below:
```{r}
f <- function(y1, y2) {
  if (y1 > 0 && y2 > 0) {
    return((1/8) * y1 * exp(-(y1 + y2) / 2))
  } else {
    return(0)
  }
}

outer_integral <- function(y1) {
  integrate(function(y2) f(y1, y2), lower = 0, upper = 1)$value
}

result <- integrate(outer_integral, lower = 1, upper = Inf)

cat("The probability P(Y1 > 1, Y2 < 1) is:", result$value, "\n")


```

